# Generated by Django 5.0.4 on 2024-04-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=20)),
                ('quantite', models.FloatField()),
                ('prix_vente', models.FloatField()),
                ('ref_Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vente.category')),
            ],
        ),
    ]
